name: Publish
on:
  # Enable manual run
  workflow_dispatch:
    inputs:
      package:
        type: choice
        description: "Which package are you using?"
        required: true
        default: "voicemeet"
        options:
          - voicemeet

jobs:
  publish:
    name: Publish
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v5

      - name: Get version
        id: get_version
        shell: pwsh
        run: |
          $xml = [xml](Get-Content ".\automatic\$env:PKG\$env:PKG.nuspec")
          $version = $xml.package.metadata.version
          
          echo "choco_version=$version" >> $env:GITHUB_OUTPUT
        env:
          PKG: ${{ github.event.inputs.package }}

      - name: Print version
        shell: pwsh
        run: |
          echo "VERSION: $env:VER"
        env:
          VER: ${{ steps.get_version.outputs.choco_version }}

      - name: Package
        shell: pwsh
        run: choco pack ".\automatic\$env:PKG\$env:PKG.nuspec"
        env:
          PKG: ${{ github.event.inputs.package }}

      - name: Push
        shell: pwsh
        run: choco push ".\$env:PKG.$env:VER.nupkg" --api-key="$env:API_KEY" --source https://push.chocolatey.org/ -d
        env:
          PKG: ${{ github.event.inputs.package }}
          VER: ${{ steps.get_version.outputs.choco_version }}
          API_KEY: ${{ secrets.CHOCO_API_KEY }}
